# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Isabella Katarina Antolic-Soban"
email: isabella.soban@domain.com
description: "I make paintings. Check em out on my rockin' website!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "iksoban.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
category-list: ["_projects"]
permalink: /:title/
